version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"